### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by hannesdelbeke** [martinlanton/maya_script_editor_highlighter#2]
Hi, I love your plugin, it's a great little tool for Maya.
I wonder if you would consider releasing your plugin also under MIT license?
GPL means I am not allowed to use it at work by my employer.
Of course if you have strong reasons to choose GPL, I understand and won't push any further on it.
It is a nice idea to force everyone to keep things open source after all.

**Comment by martinlanton** [comment]
Yes, that's not a problem at all, I just updated the license, enjoy! :D
