### ISSUE TITLE
no highlighting anymore

### ISSUE THREAD

**Issue by hannesdelbeke** [martinlanton/maya_script_editor_highlighter#5]
first time i had this.
it's been working fine for a long time and now it suddenly doesn't.
tried reloading plugins, re open console, nothing helped.
A maya restart fixed this. so would class as a low priority bug.
![image](https://github.com/martinlanton/maya_script_editor_highlighter/assets/3758308/0fb808cf-33e3-492d-80ba-f2911ea87b0c)

**Comment by martinlanton** [comment]
@hannesdelbeke Did you share the right image? The image I can see on my end looks right to me.

**Comment by hannesdelbeke** [comment]
nope i did not share the right image. 🙈
 it looked the same but without the coloring.
it was a one-of-thing, i can't repro it.

**Comment by martinlanton** [comment]
Sounds good. I'll close the issue then. Feel free to reopen if that happens again and you can figure out a proper reproduction process.
